# Site settings
title: Kevin Lim
email: bikekevin5@gmail.com
description: A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<br />for free under the <a href="https://html5up.net/license">Creative Commons</a> license.
baseurl: "/dimension-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Kevin Lim
street_address:
city: San Francisco
state: CA
zip_code:
country: United States of America
phone:

icon: fa-leaf # Font Awesome class for your site's icon

# Social settings
facebook_url: 
github_url: http://github.com/bikekevin5
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/baikhero/
linkedin_url: https://www.linkedin.com/in/kevindeanlim/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/bikekevin5

# Build settings
markdown: kramdown

sass:
style: compressed
